<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Building;

/**
 * BuildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCount() {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('count(b.id)');
        $qb->from(Building::class,'b');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
