<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Category;
use AppBundle\Entity\Helpers\RecursiveCategoryIterator;
use \Doctrine\Common\Collections\ArrayCollection;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getChildrenCategoryIds($id) {
        if ($id == null) {
            $res = $this->createQueryBuilder('c')->select('c.id')->getQuery()->getScalarResult();
            $res = array_map(function ($arrayItem) { return $arrayItem['id'];}, $res);
            return $res;
        }
        $parentCategory = $this->findOneBy(['id' => $id]);
        $collection = $parentCategory->getChildCategories();
        $categoryIterator = new RecursiveCategoryIterator($collection);
        $recursiveIterator = new \RecursiveIteratorIterator($categoryIterator, \RecursiveIteratorIterator::SELF_FIRST);

        $res = [];

        foreach ($recursiveIterator as $index => $childCategory)
        {
            $res[] = $childCategory->getId();
        }

        return $res;
    }
}
