<?php

namespace AppBundle\Repository;

/**
 * FirmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirmRepository extends \Doctrine\ORM\EntityRepository
{
}
